In [1]:
import numpy as np
import torch

In [9]:
#bt = np.asarray([[.05,.9,.05],[.6,.2,.2]])
bt = np.random.rand(10,4)
n,d=np.shape(bt)
print(n,' samples, ', d, ' dimensions')
print("bt:", bt)
print("bt square", ((bt * bt)))
print("bt square other", ((bt * bt))**2)

10  samples,  4  dimensions
bt: [[0.57785936 0.39151546 0.59197849 0.78576205]
 [0.34136028 0.20968787 0.79203336 0.95061982]
 [0.53708904 0.51845086 0.7464378  0.65044653]
 [0.20352513 0.29202643 0.05684    0.244871  ]
 [0.72886243 0.34209179 0.69975636 0.20788619]
 [0.68088975 0.01211162 0.41752502 0.4265723 ]
 [0.7100073  0.37634037 0.82738092 0.84562135]
 [0.65795959 0.52743263 0.20488696 0.34683353]
 [0.65254166 0.31376238 0.09608578 0.64805133]
 [0.73422956 0.65868638 0.90698419 0.99690001]]
bt square [[3.33921438e-01 1.53284355e-01 3.50438536e-01 6.17421997e-01]
 [1.16526843e-01 4.39690017e-02 6.27316836e-01 9.03678042e-01]
 [2.88464639e-01 2.68791289e-01 5.57169395e-01 4.23080687e-01]
 [4.14224782e-02 8.52794346e-02 3.23078529e-03 5.99618080e-02]
 [5.31240439e-01 1.17026792e-01 4.89658970e-01 4.32166697e-02]
 [4.63610855e-01 1.46691319e-04 1.74327142e-01 1.81963923e-01]
 [5.04110362e-01 1.41632076e-01 6.84559193e-01 7.15075461e-01]
 [4.32910823e-01 2.78185176e-01 4.19786648e-02

In [10]:
l2_err = np.sqrt(np.sum(((bt * bt)) ** 2, 0))
print("activation of nodes\n", bt)
print("calc l2 error", l2_err)
print("mean l2 error", np.mean(l2_err))
print("sum l2 error", np.sum(l2_err))

activation of nodes
 [[0.57785936 0.39151546 0.59197849 0.78576205]
 [0.34136028 0.20968787 0.79203336 0.95061982]
 [0.53708904 0.51845086 0.7464378  0.65044653]
 [0.20352513 0.29202643 0.05684    0.244871  ]
 [0.72886243 0.34209179 0.69975636 0.20788619]
 [0.68088975 0.01211162 0.41752502 0.4265723 ]
 [0.7100073  0.37634037 0.82738092 0.84562135]
 [0.65795959 0.52743263 0.20488696 0.34683353]
 [0.65254166 0.31376238 0.09608578 0.64805133]
 [0.73422956 0.65868638 0.90698419 0.99690001]]
calc l2 error [1.27304209 0.64344823 1.49803556 1.76217236]
mean l2 error 1.2941745623670744
sum l2 error 5.176698249468298


In [11]:
sq_err_per_dim_sample = bt*bt
print("sq_err_per_dim_sample:")
print(sq_err_per_dim_sample)

sq_err_per_dim_sample:
[[3.33921438e-01 1.53284355e-01 3.50438536e-01 6.17421997e-01]
 [1.16526843e-01 4.39690017e-02 6.27316836e-01 9.03678042e-01]
 [2.88464639e-01 2.68791289e-01 5.57169395e-01 4.23080687e-01]
 [4.14224782e-02 8.52794346e-02 3.23078529e-03 5.99618080e-02]
 [5.31240439e-01 1.17026792e-01 4.89658970e-01 4.32166697e-02]
 [4.63610855e-01 1.46691319e-04 1.74327142e-01 1.81963923e-01]
 [5.04110362e-01 1.41632076e-01 6.84559193e-01 7.15075461e-01]
 [4.32910823e-01 2.78185176e-01 4.19786648e-02 1.20293497e-01]
 [4.25810615e-01 9.84468308e-02 9.23247657e-03 4.19970520e-01]
 [5.39093053e-01 4.33867742e-01 8.22620326e-01 9.93809634e-01]]


In [12]:
print(np.sqrt(np.sum(sq_err_per_dim_sample, 0)))

[1.91757961 1.27303943 1.9392092  2.11624012]


In [13]:
loss_CLS_fun = torch.nn.CrossEntropyLoss(reduction='mean')
bt_t = torch.Tensor(bt)
_, preds = torch.max(bt_t, 1)
print("bt:", bt_t)
print("preds:", preds)
CLS = loss_CLS_fun(bt_t, preds)
print(CLS.item())

bt: tensor([[0.5779, 0.3915, 0.5920, 0.7858],
        [0.3414, 0.2097, 0.7920, 0.9506],
        [0.5371, 0.5185, 0.7464, 0.6504],
        [0.2035, 0.2920, 0.0568, 0.2449],
        [0.7289, 0.3421, 0.6998, 0.2079],
        [0.6809, 0.0121, 0.4175, 0.4266],
        [0.7100, 0.3763, 0.8274, 0.8456],
        [0.6580, 0.5274, 0.2049, 0.3468],
        [0.6525, 0.3138, 0.0961, 0.6481],
        [0.7342, 0.6587, 0.9070, 0.9969]])
preds: tensor([3, 3, 2, 1, 0, 0, 3, 0, 0, 3])
1.193690299987793
